import { Product, Category, Order, Employee, Customer } from './types'

export const categories: Category[] = [
  { id: '1', name: 'Fruits & Légumes', icon: '🥬', slug: 'fruits-legumes' },
  { id: '2', name: 'Viandes & Poissons', icon: '🥩', slug: 'viandes-poissons' },
  { id: '3', name: 'Céréales & Grains', icon: '🌾', slug: 'cereales-grains' },
  { id: '4', name: 'Huiles & Épices', icon: '🫒', slug: 'huiles-epices' },
  { id: '5', name: 'Boissons', icon: '🧃', slug: 'boissons' },
  { id: '6', name: 'Produits Laitiers', icon: '🥛', slug: 'produits-laitiers' },
  { id: '7', name: 'Tubercules', icon: '🥔', slug: 'tubercules' },
  { id: '8', name: 'Condiments', icon: '🧂', slug: 'condiments' },
]

export const products: Product[] = [
  // Fruits & Légumes
  {
    id: '1',
    name: 'Tomates fraîches',
    price: 500,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
    category: 'fruits-legumes',
    description: 'Tomates fraîches locales',
    stock: 50,
    isActive: true,
  },
  {
    id: '2',
    name: 'Oignons',
    price: 400,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=600&auto=format&fit=crop&q=80',
    category: 'fruits-legumes',
    description: 'Oignons de qualité',
    stock: 100,
    isActive: true,
  },
  {
    id: '3',
    name: 'Piment frais',
    price: 300,
    unit: 'botte',
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119cb665?w=600&auto=format&fit=crop&q=80',
    category: 'fruits-legumes',
    description: 'Piment frais local',
    stock: 30,
    isActive: true,
  },
  {
    id: '4',
    name: 'Aubergines',
    price: 350,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1590370054320-b9933ef74457?w=600&auto=format&fit=crop&q=80',
    category: 'fruits-legumes',
    description: 'Aubergines fraîches',
    stock: 40,
    isActive: true,
  },
  {
    id: '5',
    name: 'Gombo',
    price: 600,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1565538810844-1e119ba81b2a?w=600&auto=format&fit=crop&q=80',
    category: 'fruits-legumes',
    description: 'Gombo frais',
    stock: 25,
    isActive: true,
  },
  {
    id: '6',
    name: 'Bananes plantains',
    price: 800,
    unit: 'plateau',
    image: 'https://images.unsplash.com/photo-1566393028639-d108a42c46a7?w=600&auto=format&fit=crop&q=80',
    category: 'fruits-legumes',
    description: 'Bananes plantains mûres',
    stock: 60,
    isActive: true,
  },
  // Viandes & Poissons
  {
    id: '7',
    name: 'Poulet entier',
    price: 3500,
    unit: 'piece',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&auto=format&fit=crop&q=80',
    category: 'viandes-poissons',
    description: 'Poulet fermier local',
    stock: 20,
    isActive: true,
  },
  {
    id: '8',
    name: 'Boeuf (viande)',
    price: 4000,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1588168333986-5078647a5ab0?w=600&auto=format&fit=crop&q=80',
    category: 'viandes-poissons',
    description: 'Viande de boeuf fraîche',
    stock: 15,
    isActive: true,
  },
  {
    id: '9',
    name: 'Poisson Tilapia',
    price: 2500,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=600&auto=format&fit=crop&q=80',
    category: 'viandes-poissons',
    description: 'Tilapia frais',
    stock: 30,
    isActive: true,
  },
  {
    id: '10',
    name: 'Crevettes',
    price: 5000,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
    category: 'viandes-poissons',
    description: 'Crevettes fraîches',
    stock: 10,
    isActive: true,
  },
  // Céréales & Grains
  {
    id: '11',
    name: 'Riz local',
    price: 1200,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    category: 'cereales-grains',
    description: 'Riz de qualité',
    stock: 200,
    isActive: true,
  },
  {
    id: '12',
    name: 'Attieke',
    price: 500,
    unit: 'sachet',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&auto=format&fit=crop&q=80',
    category: 'cereales-grains',
    description: 'Attieke traditionnel',
    stock: 150,
    isActive: true,
  },
  {
    id: '13',
    name: 'Semoule de maïs',
    price: 800,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=600&auto=format&fit=crop&q=80',
    category: 'cereales-grains',
    description: 'Semoule de maïs',
    stock: 80,
    isActive: true,
  },
  // Huiles & Épices
  {
    id: '14',
    name: 'Huile de palme',
    price: 1500,
    unit: 'L',
    image: 'https://images.unsplash.com/photo-1614749610992-0b73c4d21650?w=600&auto=format&fit=crop&q=80',
    category: 'huiles-epices',
    description: 'Huile de palme rouge',
    stock: 50,
    isActive: true,
  },
  {
    id: '15',
    name: 'Huile végétale',
    price: 2000,
    unit: 'L',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    category: 'huiles-epices',
    description: 'Huile végétale raffinée',
    stock: 60,
    isActive: true,
  },
  {
    id: '16',
    name: 'Cube Maggi',
    price: 100,
    unit: 'piece',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=600&auto=format&fit=crop&q=80',
    category: 'huiles-epices',
    description: 'Cube de bouillon',
    stock: 500,
    isActive: true,
  },
  // Boissons
  {
    id: '17',
    name: 'Eau minérale',
    price: 500,
    unit: 'L',
    image: 'https://images.unsplash.com/photo-1560023907-5f679d1f3b86?w=600&auto=format&fit=crop&q=80',
    category: 'boissons',
    description: 'Eau minérale 1.5L',
    stock: 100,
    isActive: true,
  },
  {
    id: '18',
    name: 'Jus de bissap',
    price: 1000,
    unit: 'L',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    category: 'boissons',
    description: 'Jus de bissap naturel',
    stock: 30,
    isActive: true,
  },
  // Tubercules
  {
    id: '19',
    name: 'Igname',
    price: 700,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1595855759920-86582396756a?w=600&auto=format&fit=crop&q=80',
    category: 'tubercules',
    description: 'Igname fraîche',
    stock: 80,
    isActive: true,
  },
  {
    id: '20',
    name: 'Manioc',
    price: 400,
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1590005354167-6da97870c913?w=600&auto=format&fit=crop&q=80',
    category: 'tubercules',
    description: 'Manioc frais',
    stock: 70,
    isActive: true,
  },
]

export const districts = [
  'Air France',
  'Ahougnassou',
  'Belleville',
  'Commerce',
  'Dar Es Salam',
  'Koko',
  'Konankankro',
  'N\'gattakro',
  'Nimbo',
  'Zone industrielle',
]

export const paymentMethods = [
  { id: 'orange_money', name: 'Orange Money', icon: '🟠' },
  { id: 'mtn_money', name: 'MTN Money', icon: '🟡' },
  { id: 'moov_money', name: 'Moov Money', icon: '🔵' },
  { id: 'wave', name: 'Wave', icon: '🌊' },
  { id: 'cash', name: 'Paiement à la livraison', icon: '💵' },
]

// Demo data for dashboard
export const demoOrders: Order[] = [
  {
    id: 'ORD-001',
    customer: {
      id: 'C1',
      name: 'Kouamé Yao',
      phone: '+225 07 12 34 56',
      address: 'Rue du Commerce, près de la pharmacie',
      district: 'Commerce',
      createdAt: new Date('2024-01-15'),
    },
    items: [
      { product: products[0], quantity: 2 },
      { product: products[6], quantity: 1 },
    ],
    subtotal: 4500,
    deliveryFee: 500,
    total: 5000,
    paymentMethod: 'orange_money',
    status: 'delivered',
    createdAt: new Date('2024-01-20T10:30:00'),
  },
  {
    id: 'ORD-002',
    customer: {
      id: 'C2',
      name: 'Adjoua Koffi',
      phone: '+225 05 98 76 54',
      address: 'Avenue principale, face au marché',
      district: 'Belleville',
      createdAt: new Date('2024-01-16'),
    },
    items: [
      { product: products[10], quantity: 5 },
      { product: products[13], quantity: 2 },
    ],
    subtotal: 9000,
    deliveryFee: 500,
    total: 9500,
    paymentMethod: 'mtn_money',
    status: 'delivering',
    createdAt: new Date('2024-01-20T14:15:00'),
  },
  {
    id: 'ORD-003',
    customer: {
      id: 'C3',
      name: 'Bamba Moussa',
      phone: '+225 01 23 45 67',
      address: 'Quartier résidentiel, villa 23',
      district: 'Air France',
      createdAt: new Date('2024-01-17'),
    },
    items: [
      { product: products[7], quantity: 2 },
      { product: products[8], quantity: 3 },
    ],
    subtotal: 15500,
    deliveryFee: 500,
    total: 16000,
    paymentMethod: 'wave',
    status: 'pending',
    createdAt: new Date('2024-01-20T16:45:00'),
  },
  {
    id: 'ORD-004',
    customer: {
      id: 'C4',
      name: 'Traoré Aminata',
      phone: '+225 07 65 43 21',
      address: 'Près de l\'école primaire',
      district: 'Koko',
      createdAt: new Date('2024-01-18'),
    },
    items: [
      { product: products[5], quantity: 2 },
      { product: products[11], quantity: 4 },
    ],
    subtotal: 3600,
    deliveryFee: 500,
    total: 4100,
    paymentMethod: 'cash',
    status: 'confirmed',
    createdAt: new Date('2024-01-20T09:00:00'),
  },
  {
    id: 'ORD-005',
    customer: {
      id: 'C5',
      name: 'Koné Ibrahim',
      phone: '+225 05 11 22 33',
      address: 'Derrière la mosquée centrale',
      district: 'Dar Es Salam',
      createdAt: new Date('2024-01-19'),
    },
    items: [
      { product: products[18], quantity: 5 },
      { product: products[14], quantity: 2 },
    ],
    subtotal: 7500,
    deliveryFee: 500,
    total: 8000,
    paymentMethod: 'moov_money',
    status: 'cancelled',
    createdAt: new Date('2024-01-19T11:30:00'),
  },
]

export const demoEmployees: Employee[] = [
  {
    id: 'E1',
    name: 'Ouattara Mamadou',
    email: 'mamadou@gwabo.ci',
    phone: '+225 07 00 00 01',
    role: 'admin',
    isActive: true,
    createdAt: new Date('2023-06-01'),
  },
  {
    id: 'E2',
    name: 'Coulibaly Fatou',
    email: 'fatou@gwabo.ci',
    phone: '+225 07 00 00 02',
    role: 'accountant',
    isActive: true,
    createdAt: new Date('2023-07-15'),
  },
  {
    id: 'E3',
    name: 'Diallo Sekou',
    email: 'sekou@gwabo.ci',
    phone: '+225 07 00 00 03',
    role: 'order_manager',
    isActive: true,
    createdAt: new Date('2023-08-01'),
  },
  {
    id: 'E4',
    name: 'N\'Guessan Aya',
    email: 'aya@gwabo.ci',
    phone: '+225 07 00 00 04',
    role: 'delivery_agent',
    isActive: true,
    createdAt: new Date('2023-09-10'),
  },
  {
    id: 'E5',
    name: 'Brou Kouadio',
    email: 'kouadio@gwabo.ci',
    phone: '+225 07 00 00 05',
    role: 'customer_support',
    isActive: false,
    createdAt: new Date('2023-10-20'),
  },
]

export const dashboardStats = {
  totalRevenue: 2450000,
  totalOrders: 156,
  pendingDeliveries: 12,
  deliveredOrders: 138,
  activeCustomers: 89,
  activeProducts: products.filter(p => p.isActive).length,
}

export const salesData = [
  { month: 'Jan', sales: 180000 },
  { month: 'Fév', sales: 220000 },
  { month: 'Mar', sales: 195000 },
  { month: 'Avr', sales: 280000 },
  { month: 'Mai', sales: 310000 },
  { month: 'Juin', sales: 265000 },
  { month: 'Juil', sales: 340000 },
  { month: 'Août', sales: 295000 },
  { month: 'Sep', sales: 320000 },
  { month: 'Oct', sales: 380000 },
  { month: 'Nov', sales: 420000 },
  { month: 'Déc', sales: 450000 },
]

export const topProducts = [
  { name: 'Riz local', sales: 45, revenue: 54000 },
  { name: 'Poulet entier', sales: 38, revenue: 133000 },
  { name: 'Huile végétale', sales: 32, revenue: 64000 },
  { name: 'Tomates fraîches', sales: 28, revenue: 14000 },
  { name: 'Attieke', sales: 25, revenue: 12500 },
]
